# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
    - name: Add path for Poetry
      run: |
        echo "$HOME/.poetry/bin" >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        poetry install --no-interaction
    - name: black!
      run:
        poetry run black . --check
    - name: isort!
      run:
        poetry run isort . --check
    - name: autoflake!
      run:
        poetry run autoflake -r --check --remove-all-unused-imoprts --ignore-init-module-imports --remove-unused-variables .
    - name: Test with pytest
      run: |
        pytest
